FRAME_RATE = 61

WINDOW_WIDTH = 1080
WINDOW_HEIGHT = 720

MAP_WIDTH = WINDOW_HEIGHT
MAP_HEIGHT = WINDOW_HEIGHT

MENU_WIDTH = WINDOW_WIDTH - MAP_WIDTH
MENU_HEIGHT = WINDOW_HEIGHT

SQUARE_ROW = 5
SQUARE_NUMBER = SQUARE_ROW ** 2

SQUARE_SIZE = 64
